[package]
name = "cdchunking"
version = "0.2.1"
authors = ["Remi Rampin <remirampin@gmail.com>"]
description = "Content-defined chunking"
documentation = "https://remram44.github.io/cdchunking-rs/index.html"
readme = "README.md"
repository = "https://github.com/remram44/cdchunking-rs"
keywords = ["chunks", "cdc", "content", "defined", "chunking"]
license = "MIT"

[dependencies]

[dev-dependencies]
rand = "0.4"
